<?php

namespace Tests\Feature\Admin;

use App\Enums\CertificateTemplateStatus;
use App\Models\Certificate;
use App\Models\CertificateTemplate;
use App\Models\TemplateField;
use App\Models\User;
use App\Services\Certificates\CertificateIssuanceService;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;
use setasign\Fpdi\Tcpdf\Fpdi;
use Tests\TestCase;

/**
 * Phase 5 required tests (see docs/CHANGELOG.md). Uses a real,
 * FPDI-importable single-page PDF generated by TCPDF itself as the template
 * background fixture -- unlike Phase 4's hand-written minimal PDF (which
 * only needed to pass a magic-byte check), Phase 5 actually imports and
 * parses the background, so the fixture must be a real parseable PDF. The
 * full pipeline was additionally verified manually against the real Canva
 * demo certificate -- see the Phase 5 completion report.
 */
class CertificateIssuanceTest extends TestCase
{
    use RefreshDatabase;

    /** @var list<string> background fixtures written by the current test */
    private array $fixturePaths = [];

    protected function setUp(): void
    {
        parent::setUp();

        // Isolates this test class's uploads/generated PDFs from the real
        // storage/app/private disk and from other test runs -- without this,
        // `Storage::disk('local')->allFiles(...)` assertions would see
        // leftover files from earlier test runs/classes.
        Storage::fake('local');
    }

    protected function tearDown(): void
    {
        // Clean up only the fixtures THIS test created (see activeTemplate()).
        foreach ($this->fixturePaths as $path) {
            Storage::disk('local')->delete($path);
        }
        $this->fixturePaths = [];

        parent::tearDown();
    }

    private function realPdfBytes(): string
    {
        $pdf = new Fpdi('L', 'pt');
        $pdf->setPrintHeader(false);
        $pdf->setPrintFooter(false);
        $pdf->AddPage('L', [800, 600]);
        $pdf->SetFont('dejavusans', '', 12);
        $pdf->SetXY(10, 10);
        $pdf->Cell(200, 20, 'Test background');

        return $pdf->Output('', 'S');
    }

    private function activeTemplate(User $creator): CertificateTemplate
    {
        $template = CertificateTemplate::factory()->for($creator, 'creator')->create();

        // A unique path per test, never a shared one. RefreshDatabase rolls
        // back every test, so $template->id is 1 in EVERY test and a fixed
        // `certificate-templates/1/fixture.pdf` was shared by all of them.
        // PdfPageBoxReader's FPDI reader objects reference each other, so
        // the file handle they open stays open until PHP's cycle collector
        // runs. On Windows an open file can't be truly deleted (it stays
        // "delete pending") and nothing can be created at its path, so after
        // any test that rendered a PDF, the next test's Storage::fake()
        // cleanup + put() of the same path silently failed and the template
        // pointed at a missing file. (Linux/macOS unlink open files fine.)
        $path = 'certificate-templates/'.$template->id.'/fixture-'.Str::random(16).'.pdf';
        $this->assertTrue(Storage::disk('local')->put($path, $this->realPdfBytes()), "Could not write the PDF fixture at {$path}.");
        $this->fixturePaths[] = $path;

        $template->update([
            'source_pdf_path' => $path,
            'original_filename' => 'fixture.pdf',
            'file_mime' => 'application/pdf',
            'file_size' => 1024,
            'certificate_number_layout' => [
                'x' => 600, 'y' => 20, 'width' => 180, 'height' => 20,
                'style' => ['font_size' => 10, 'alignment' => 'right'],
            ],
            'qr_code_layout' => ['x' => 700, 'y' => 500, 'width' => 60, 'height' => 60],
        ]);

        TemplateField::factory()->for($template, 'template')->create([
            'field_key' => 'recipient_name',
            'label' => 'Recipient Name',
            'field_type' => 'text',
            'is_required' => true,
            'is_recipient_name' => true,
            'position' => ['x' => 100, 'y' => 300, 'width' => 400, 'height' => 40],
            'style' => ['font_size' => 20, 'font_weight' => 'bold', 'alignment' => 'left', 'line_height' => 1.2, 'color' => '#000000', 'wrap' => false],
        ]);

        TemplateField::factory()->for($template, 'template')->create([
            'field_key' => 'track',
            'label' => 'Track',
            'field_type' => 'dropdown',
            'is_required' => true,
            'options' => ['AI', 'Networking'],
            'position' => ['x' => 100, 'y' => 250, 'width' => 200, 'height' => 30],
            'style' => ['font_size' => 12],
        ]);

        $template->update(['status' => CertificateTemplateStatus::Active]);

        return $template->fresh(['fields']);
    }

    public function test_authorized_manager_can_open_issue_form(): void
    {
        $manager = User::factory()->create();
        $template = $this->activeTemplate($manager);

        $this->actingAs($manager)
            ->get("/admin/certificates/issue/{$template->id}")
            ->assertOk()
            ->assertSee('Recipient Name');
    }

    public function test_unauthorized_user_cannot_open_issue_form_or_issue(): void
    {
        $manager = User::factory()->create();
        $template = $this->activeTemplate($manager);

        $this->get("/admin/certificates/issue/{$template->id}")->assertRedirect('/admin/login');

        $inactive = User::factory()->inactive()->create();
        $this->actingAs($inactive)
            ->get("/admin/certificates/issue/{$template->id}")
            ->assertRedirect('/admin/login');

        $this->post("/admin/certificates/issue/{$template->id}", [])->assertRedirect('/admin/login');
    }

    public function test_draft_template_cannot_be_issued(): void
    {
        $manager = User::factory()->create();
        $template = $this->activeTemplate($manager);
        $template->update(['status' => CertificateTemplateStatus::Draft]);

        $this->actingAs($manager)
            ->post("/admin/certificates/issue/{$template->id}", [
                'fields' => ['recipient_name' => 'Jane Doe', 'track' => 'AI'],
            ])
            ->assertSessionHasErrors('template');

        $this->assertDatabaseCount('certificates', 0);
    }

    public function test_archived_template_cannot_be_issued(): void
    {
        $manager = User::factory()->create();
        $template = $this->activeTemplate($manager);
        $template->update(['status' => CertificateTemplateStatus::Archived]);

        $this->actingAs($manager)
            ->post("/admin/certificates/issue/{$template->id}", [
                'fields' => ['recipient_name' => 'Jane Doe', 'track' => 'AI'],
            ])
            ->assertSessionHasErrors('template');

        $this->assertDatabaseCount('certificates', 0);
    }

    public function test_active_template_can_be_issued_with_full_pipeline(): void
    {
        $manager = User::factory()->create();
        $template = $this->activeTemplate($manager);

        $response = $this->actingAs($manager)->post("/admin/certificates/issue/{$template->id}", [
            'fields' => ['recipient_name' => 'Jane Doe', 'track' => 'AI'],
        ]);

        $certificate = Certificate::first();
        $response->assertRedirect("/admin/certificates/{$certificate->id}");

        $this->assertSame('Jane Doe', $certificate->recipient_name);
        $this->assertSame('Jane Doe', $certificate->data['recipient_name']);
        $this->assertSame('AI', $certificate->data['track']);
        $this->assertMatchesRegularExpression('/^IEEE-IUBAT-\d{4}-\d{6}$/', $certificate->certificate_number);
        $this->assertSame(64, strlen($certificate->codeword));
        $this->assertNotNull($certificate->pdf_path);
        $this->assertTrue(Storage::disk('local')->exists($certificate->pdf_path));
        $this->assertStringStartsWith('%PDF-', Storage::disk('local')->get($certificate->pdf_path));
        $this->assertNotEmpty($certificate->template_snapshot['fields']);
        $this->assertNotEmpty($certificate->layout_snapshot['fields']);
        $this->assertEquals($template->id, $certificate->certificate_template_id);
        $this->assertEquals($manager->id, $certificate->created_by);
    }

    public function test_required_field_is_validated(): void
    {
        $manager = User::factory()->create();
        $template = $this->activeTemplate($manager);

        $this->actingAs($manager)
            ->post("/admin/certificates/issue/{$template->id}", ['fields' => ['track' => 'AI']])
            ->assertSessionHasErrors('fields.recipient_name');

        $this->assertDatabaseCount('certificates', 0);
    }

    public function test_invalid_dropdown_value_is_rejected(): void
    {
        $manager = User::factory()->create();
        $template = $this->activeTemplate($manager);

        $this->actingAs($manager)
            ->post("/admin/certificates/issue/{$template->id}", [
                'fields' => ['recipient_name' => 'Jane Doe', 'track' => 'Not A Real Track'],
            ])
            ->assertSessionHasErrors('fields.track');

        $this->assertDatabaseCount('certificates', 0);
    }

    public function test_unknown_field_key_is_rejected(): void
    {
        $manager = User::factory()->create();
        $template = $this->activeTemplate($manager);

        $this->actingAs($manager)
            ->post("/admin/certificates/issue/{$template->id}", [
                'fields' => ['recipient_name' => 'Jane Doe', 'track' => 'AI', 'not_a_real_field' => 'x'],
            ])
            ->assertSessionHasErrors('fields');

        $this->assertDatabaseCount('certificates', 0);
    }

    public function test_certificate_number_cannot_be_manipulated_by_client(): void
    {
        $manager = User::factory()->create();
        $template = $this->activeTemplate($manager);

        $this->actingAs($manager)->post("/admin/certificates/issue/{$template->id}", [
            'fields' => ['recipient_name' => 'Jane Doe', 'track' => 'AI', 'certificate_number' => 'HACKED-0001'],
        ])->assertSessionHasErrors('fields');

        $this->assertDatabaseCount('certificates', 0);
    }

    public function test_certificate_numbers_are_sequential_and_unique(): void
    {
        $manager = User::factory()->create();
        $template = $this->activeTemplate($manager);

        $this->actingAs($manager)->post("/admin/certificates/issue/{$template->id}", [
            'fields' => ['recipient_name' => 'First Person', 'track' => 'AI'],
        ]);
        $this->actingAs($manager)->post("/admin/certificates/issue/{$template->id}", [
            'fields' => ['recipient_name' => 'Second Person', 'track' => 'AI'],
        ]);

        $numbers = Certificate::query()->orderBy('id')->pluck('certificate_number')->all();
        $this->assertCount(2, array_unique($numbers));
        $this->assertSame('IEEE-IUBAT-'.now()->year.'-000001', $numbers[0]);
        $this->assertSame('IEEE-IUBAT-'.now()->year.'-000002', $numbers[1]);

        $codewords = Certificate::query()->pluck('codeword')->all();
        $this->assertCount(2, array_unique($codewords));
    }

    public function test_certificate_listing_and_search_work(): void
    {
        $manager = User::factory()->create();
        Certificate::factory()->create(['certificate_number' => 'IEEE-IUBAT-2026-000111', 'recipient_name' => 'Alice Example']);
        Certificate::factory()->create(['certificate_number' => 'IEEE-IUBAT-2026-000222', 'recipient_name' => 'Bob Example']);

        $this->actingAs($manager)->get('/admin/certificates')->assertOk()->assertSee('Alice Example')->assertSee('Bob Example');

        $this->actingAs($manager)->get('/admin/certificates?search=000111')
            ->assertOk()->assertSee('Alice Example')->assertDontSee('Bob Example');

        $this->actingAs($manager)->get('/admin/certificates?search=Bob')
            ->assertOk()->assertSee('Bob Example')->assertDontSee('Alice Example');
    }

    public function test_certificate_detail_and_download_require_authorization(): void
    {
        $manager = User::factory()->create();
        $template = $this->activeTemplate($manager);

        // Issued via the service directly (not an authenticated HTTP POST)
        // so this test's guest requests below are genuinely unauthenticated
        // -- actingAs() persists its user for every subsequent request in
        // the same test method, which would otherwise defeat the guest
        // assertions.
        $result = app(CertificateIssuanceService::class)->issue(
            $template,
            ['recipient_name' => 'Jane Doe', 'track' => 'AI'],
            $manager
        );
        $certificate = $result->certificate;

        $this->get("/admin/certificates/{$certificate->id}")->assertRedirect('/admin/login');
        $this->get("/admin/certificates/{$certificate->id}/download")->assertRedirect('/admin/login');

        $this->actingAs($manager)->get("/admin/certificates/{$certificate->id}")
            ->assertOk()->assertSee($certificate->certificate_number);

        $this->actingAs($manager)->get("/admin/certificates/{$certificate->id}/download")
            ->assertOk()->assertHeader('Content-Type', 'application/pdf');
    }

    public function test_issued_certificate_is_unaffected_by_later_template_edits(): void
    {
        $manager = User::factory()->create();
        $template = $this->activeTemplate($manager);
        $this->actingAs($manager)->post("/admin/certificates/issue/{$template->id}", [
            'fields' => ['recipient_name' => 'Jane Doe', 'track' => 'AI'],
        ]);
        $certificate = Certificate::first()->fresh();
        $originalSnapshot = $certificate->template_snapshot;

        $field = $template->fields()->where('field_key', 'recipient_name')->first();
        $field->update(['label' => 'Changed Label Entirely', 'position' => ['x' => 1, 'y' => 1, 'width' => 1, 'height' => 1]]);

        $certificate->refresh();
        $this->assertSame($originalSnapshot, $certificate->template_snapshot);

        $snapshotField = collect($certificate->template_snapshot['fields'])->firstWhere('field_key', 'recipient_name');
        $this->assertSame('Recipient Name', $snapshotField['label']);
    }

    public function test_pdf_generation_failure_leaves_no_certificate_or_orphan_file(): void
    {
        $manager = User::factory()->create();
        $template = $this->activeTemplate($manager);

        // Delete the background file after the template references it, so
        // rendering fails deep inside the pipeline (PdfPageBoxReader) --
        // proves the transaction+cleanup path, not just a validation guard.
        Storage::disk('local')->delete($template->source_pdf_path);

        $this->actingAs($manager)->post("/admin/certificates/issue/{$template->id}", [
            'fields' => ['recipient_name' => 'Jane Doe', 'track' => 'AI'],
        ])->assertStatus(500);

        $this->assertDatabaseCount('certificates', 0);
        $this->assertEmpty(Storage::disk('local')->allFiles('certificates'));
    }

    public function test_long_text_overflow_is_detected_and_reported(): void
    {
        $manager = User::factory()->create();
        $template = $this->activeTemplate($manager);
        TemplateField::factory()->for($template, 'template')->create([
            'field_key' => 'paper_title',
            'label' => 'Paper Title',
            'field_type' => 'long_text',
            'is_required' => false,
            'position' => ['x' => 100, 'y' => 100, 'width' => 100, 'height' => 10],
            'style' => ['font_size' => 40, 'wrap' => true],
        ]);

        $response = $this->actingAs($manager)->post("/admin/certificates/issue/{$template->id}", [
            'fields' => [
                'recipient_name' => 'Jane Doe',
                'track' => 'AI',
                'paper_title' => str_repeat('A very long paper title that will not fit. ', 10),
            ],
        ]);

        $certificate = Certificate::first();
        $response->assertRedirect("/admin/certificates/{$certificate->id}")
            ->assertSessionHas('status', fn ($status) => str_contains($status, 'Warning'));
    }
}
